# GitLab CI/CD Workflow for Node.js Applications
#
# This template provides a robust starting point for building, testing, and
# securing a typical Node.js application. It includes stages for dependency
# management, linting, unit testing, security scanning, and Docker image creation.
#
# For more information on GitLab CI, see:
# https://docs.gitlab.com/ee/ci/

image: node:18

stages:
  - lint
  - test
  - security-scan
  - build

# Cache node_modules to speed up subsequent jobs
cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm test

security-scan:
  stage: security-scan
  script:
    - npm audit --audit-level=high

build-docker:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  script:
    - docker build -t your-dockerhub-username/your-app-name:latest .
    - docker push your-dockerhub-username/your-app-name:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
