# GitHub Actions workflow for complexity analysis
# This workflow will be triggered on push and pull requests.
# It will use lizard and radon to analyze the complexity of the Python code.
name: Complexity Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lizard radon[colorama] lizard-cognitive-complexity
      - name: Generate lizard report
        run: lizard . --xml --CCN > lizard-report.xml
      - name: Analyze lizard report
        run: python check_lizard_metrics.py lizard-report.xml --cc 15 --cognitive-complexity 10
      - name: Run radon for Maintainability Index
        run: radon mi . --max B -s
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "."
          fail_above: 25
          warn_above: 15
