name: MLOps Training Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[git]"
      - name: Setup DVC
        run: python setup_dvc.py
      - name: Validate data
        run: python validate_data.py
      - name: Train model
        run: python train_predictor.py
      - name: Add data and model to DVC
        run: |
          dvc add workflow_runs.csv
          dvc add predictor.joblib
      - name: Push data to DVC remote
        run: dvc push
      - name: Commit DVC metadata
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update DVC metadata"
          file_pattern: "*.dvc .dvc/config"
